const products = [
    {
      id: 201,
      name: "Nike Air Max",
      category: "Shoes",
      price: 35000,
      description: "Comfortable and stylish running shoes",
      imageUrl: "path/to/nike-air-max.jpg",
      rating: 4.8,
      stock: 12,
      brand: "Nike"
    },
    {
      id: 202,
      name: "Adidas Ultraboost",
      category: "Shoes",
      price: 40000,
      description: "High-performance running shoes with superior cushioning",
      imageUrl: "path/to/adidas-ultraboost.jpg",
      rating: 4.7,
      stock: 8,
      brand: "Adidas"
    },
    {
      id: 203,
      name: "Gucci Tote Bag",
      category: "Bags",
      price: 150000,
      description: "Luxurious leather tote bag for everyday use",
      imageUrl: "path/to/gucci-tote.jpg",
      rating: 4.9,
      stock: 4,
      brand: "Gucci"
    },
    {
      id: 204,
      name: "Ray-Ban Aviator Sunglasses",
      category: "Accessories",
      price: 25000,
      description: "Classic aviator sunglasses with polarized lenses",
      imageUrl: "path/to/rayban-aviator.jpg",
      rating: 4.6,
      stock: 15,
      brand: "Ray-Ban"
    },
    {
      id: 205,
      name: "Levi's Denim Jacket",
      category: "Clothes",
      price: 45000,
      description: "Timeless denim jacket for a casual look",
      imageUrl: "path/to/levis-jacket.jpg",
      rating: 4.5,
      stock: 10,
      brand: "Levi's"
    },
    {
      id: 206,
      name: "Hermès Silk Scarf",
      category: "Accessories",
      price: 120000,
      description: "Elegant silk scarf with intricate patterns",
      imageUrl: "path/to/hermes-scarf.jpg",
      rating: 4.9,
      stock: 6,
      brand: "Hermès"
    },
    {
      id: 207,
      name: "Converse Chuck Taylor",
      category: "Shoes",
      price: 20000,
      description: "Classic canvas sneakers for everyday wear",
      imageUrl: "path/to/converse-chuck.jpg",
      rating: 4.7,
      stock: 20,
      brand: "Converse"
    },
    {
      id: 208,
      name: "Prada Handbag",
      category: "Bags",
      price: 250000,
      description: "Designer handbag with sleek leather finish",
      imageUrl: "path/to/prada-handbag.jpg",
      rating: 4.8,
      stock: 3,
      brand: "Prada"
    },
    {
      id: 209,
      name: "Under Armour Sportswear T-shirt",
      category: "Clothes",
      price: 10000,
      description: "Moisture-wicking t-shirt for active lifestyle",
      imageUrl: "path/to/ua-tshirt.jpg",
      rating: 4.6,
      stock: 25,
      brand: "Under Armour"
    },
    {
      id: 210,
      name: "Casio G-Shock Watch",
      category: "Accessories",
      price: 18000,
      description: "Durable digital watch with multiple features",
      imageUrl: "path/to/casio-gshock.jpg",
      rating: 4.8,
      stock: 12,
      brand: "Casio"
    },
    {
      id: 211,
      name: "Puma Running Shoes",
      category: "Shoes",
      price: 30000,
      description: "Lightweight running shoes for high performance",
      imageUrl: "path/to/puma-shoes.jpg",
      rating: 4.5,
      stock: 18,
      brand: "Puma"
    },
    {
      id: 212,
      name: "Michael Kors Shoulder Bag",
      category: "Bags",
      price: 95000,
      description: "Chic shoulder bag with gold accents",
      imageUrl: "path/to/mk-bag.jpg",
      rating: 4.7,
      stock: 7,
      brand: "Michael Kors"
    },
    {
      id: 213,
      name: "Armani Exchange Leather Belt",
      category: "Accessories",
      price: 15000,
      description: "Premium leather belt with sleek buckle",
      imageUrl: "path/to/armani-belt.jpg",
      rating: 4.6,
      stock: 30,
      brand: "Armani Exchange"
    },
    {
      id: 214,
      name: "Zara Formal Blazer",
      category: "Clothes",
      price: 55000,
      description: "Sharp formal blazer for business and events",
      imageUrl: "path/to/zara-blazer.jpg",
      rating: 4.7,
      stock: 9,
      brand: "Zara"
    },
    {
      id: 215,
      name: "Fossil Leather Wallet",
      category: "Accessories",
      price: 12000,
      description: "Compact leather wallet with multiple compartments",
      imageUrl: "path/to/fossil-wallet.jpg",
      rating: 4.8,
      stock: 14,
      brand: "Fossil"
    },
    {
      id: 216,
      name: "Nike Zoom Pegasus",
      category: "Shoes",
      price: 38000,
      description: "Versatile running shoes with responsive cushioning",
      imageUrl: "path/to/nike-pegasus.jpg",
      rating: 4.8,
      stock: 10,
      brand: "Nike"
    },
    {
      id: 217,
      name: "Adidas NMD_R1",
      category: "Shoes",
      price: 42000,
      description: "Modern sneakers with a sleek design",
      imageUrl: "path/to/adidas-nmd.jpg",
      rating: 4.7,
      stock: 15,
      brand: "Adidas"
    },
    {
      id: 218,
      name: "Gucci Crossbody Bag",
      category: "Bags",
      price: 180000,
      description: "Stylish crossbody bag with Gucci's signature pattern",
      imageUrl: "path/to/gucci-crossbody.jpg",
      rating: 4.9,
      stock: 5,
      brand: "Gucci"
    },
    {
      id: 219,
      name: "Ray-Ban Wayfarer Sunglasses",
      category: "Accessories",
      price: 22000,
      description: "Iconic sunglasses with a classic frame",
      imageUrl: "path/to/rayban-wayfarer.jpg",
      rating: 4.8,
      stock: 20,
      brand: "Ray-Ban"
    },
    {
      id: 220,
      name: "Levi's Slim Fit Jeans",
      category: "Clothes",
      price: 35000,
      description: "Comfortable and durable slim-fit denim",
      imageUrl: "path/to/levis-jeans.jpg",
      rating: 4.6,
      stock: 18,
      brand: "Levi's"
    },
    {
      id: 221,
      name: "Hermès Leather Wallet",
      category: "Accessories",
      price: 140000,
      description: "Elegant leather wallet with a minimalist design",
      imageUrl: "path/to/hermes-wallet.jpg",
      rating: 4.9,
      stock: 4,
      brand: "Hermès"
    },
    {
      id: 222,
      name: "Converse High Tops",
      category: "Shoes",
      price: 25000,
      description: "Iconic high-top sneakers for a casual look",
      imageUrl: "path/to/converse-high.jpg",
      rating: 4.7,
      stock: 22,
      brand: "Converse"
    },
    {
      id: 223,
      name: "Prada Backpack",
      category: "Bags",
      price: 270000,
      description: "Luxury nylon backpack for style and functionality",
      imageUrl: "path/to/prada-backpack.jpg",
      rating: 4.8,
      stock: 3,
      brand: "Prada"
    },
    {
      id: 224,
      name: "Under Armour Track Pants",
      category: "Clothes",
      price: 15000,
      description: "Comfortable track pants for workouts and casual wear",
      imageUrl: "path/to/ua-trackpants.jpg",
      rating: 4.7,
      stock: 25,
      brand: "Under Armour"
    },
    {
      id: 225,
      name: "Casio Edifice Watch",
      category: "Accessories",
      price: 30000,
      description: "Elegant chronograph watch with a sleek design",
      imageUrl: "path/to/casio-edifice.jpg",
      rating: 4.8,
      stock: 10,
      brand: "Casio"
    },
    {
      id: 226,
      name: "Puma Suede Sneakers",
      category: "Shoes",
      price: 32000,
      description: "Classic suede sneakers for everyday wear",
      imageUrl: "path/to/puma-suede.jpg",
      rating: 4.5,
      stock: 16,
      brand: "Puma"
    },
    {
      id: 227,
      name: "Michael Kors Travel Tote",
      category: "Bags",
      price: 120000,
      description: "Spacious tote bag ideal for travel",
      imageUrl: "path/to/mk-travel-tote.jpg",
      rating: 4.7,
      stock: 8,
      brand: "Michael Kors"
    },
    {
      id: 228,
      name: "Armani Exchange Cap",
      category: "Accessories",
      price: 12000,
      description: "Stylish cap with Armani Exchange branding",
      imageUrl: "path/to/armani-cap.jpg",
      rating: 4.6,
      stock: 30,
      brand: "Armani Exchange"
    },
    {
      id: 229,
      name: "Zara Casual Shirt",
      category: "Clothes",
      price: 25000,
      description: "Comfortable casual shirt for everyday style",
      imageUrl: "path/to/zara-shirt.jpg",
      rating: 4.6,
      stock: 12,
      brand: "Zara"
    },
    {
      id: 230,
      name: "Fossil Chronograph Watch",
      category: "Accessories",
      price: 45000,
      description: "Sleek chronograph watch with a leather strap",
      imageUrl: "path/to/fossil-watch.jpg",
      rating: 4.8,
      stock: 8,
      brand: "Fossil"
    }
  ];
    